INSERT INTO locations (location_cd, location_desc, location_addr) values ('BOS', 'Boston, MA', '123 Main Street, Boston, MA 01833');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('NYC', 'New York, NY', '123 Times Square, New York, NY 12345');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('DCA', 'Washington, DC', '111 Massachusetts Ave, Washington, DC 20008');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('ATL', 'Atlanta, GA', '123 Peach Road, Atlanta, GA 46127');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('LAX', 'Los Angeles, CA', '123 Main Street, Los Angeles, CA 90210');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('DEN', 'Denver, CO', '123 Main Street, Denver, CO 28812');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('LAS', 'Las Vegas, NV', '123 Main Street, Las Vegas, NV 32213');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('TEX', 'Dallas, TX', '123 Main Street, Dallas, TX 98765');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('PWM', 'Portland, ME', '123 Main Street, Portland, ME 77667');
INSERT INTO locations (location_cd, location_desc, location_addr) values ('STL', 'St. Louis, MO', '123 Main Street, St. Louis, MO 30193');